import Head from "next/head";

import BottomNavigation from "../components/BottomNavigation";
import { Text } from "@mantine/core";
import { IconHome, IconSearch, IconUser, IconAdjustments } from "@tabler/icons";

export default function Home() {
  const sections = [
    {
      key: "test1",
      icon: <IconHome />,
      component: <Main />,
    },
    {
      key: "test2",
      icon: <IconSearch />,
      component: <Search />,
    },
    {
      key: "test3",
      icon: <IconUser />,
      component: <Profile />,
    },
    {
      key: "test4",
      icon: <IconAdjustments />,
      component: <Settings />,
    },
  ];

  return (
    <div>
      <Head>
        <title>Mantine UI | Bottom navigation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BottomNavigation sections={sections} activeColor="green" />
    </div>
  );
}

const Main = () => {
  return (
    <div className="p-8 space-y-8">
      <h1 className="font-semibold tracking-tight">Home</h1>
      <Text color="dimmed">
        This demo shows a custom bottom navigation I&apos;ve built using Mantine
        UI&apos;s ActionIcon and AppShell components.
      </Text>
      <Text color="dimmed">
        Read more about Mantine UI from{" "}
        <a className="text-green-600 underline" href="https://mantine.dev/">
          here
        </a>
      </Text>
      <Text color="dimmed">You are currently in the home section</Text>
    </div>
  );
};
const Search = () => {
  return (
    <div className="p-8 space-y-8">
      <h1 className="font-semibold tracking-tight">Search</h1>
      <Text color="dimmed">You are currently in the search section</Text>
    </div>
  );
};
const Profile = () => {
  return (
    <div className="p-8 space-y-8">
      <h1 className="font-semibold tracking-tight">Profile</h1>
      <Text color="dimmed">You are currently in the profile section</Text>
    </div>
  );
};
const Settings = () => {
  return (
    <div className="p-8 space-y-8">
      <h1 className="font-semibold tracking-tight">Settings</h1>
      <Text color="dimmed">You are currently in the settings section</Text>
    </div>
  );
};
